/* tslint:disable */
/* eslint-disable */
/**
 * Crestal dashboard API - /crestal - OpenAPI 3.0
 * This is a crestal-dashboard-backend server.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Check if a given object implements the Activity interface.
 */
export function instanceOfActivity(value) {
    return true;
}
export function ActivityFromJSON(json) {
    return ActivityFromJSONTyped(json, false);
}
export function ActivityFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'action': json['action'] == null ? undefined : json['action'],
        'address': json['address'] == null ? undefined : json['address'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
    };
}
export function ActivityToJSON(json) {
    return ActivityToJSONTyped(json, false);
}
export function ActivityToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'action': value['action'],
        'address': value['address'],
        'created_at': value['createdAt'],
    };
}
