/* tslint:disable */
/* eslint-disable */
/**
 * Crestal dashboard API - /crestal - OpenAPI 3.0
 * This is a crestal-dashboard-backend server.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Check if a given object implements the APIKey interface.
 */
export function instanceOfAPIKey(value) {
    return true;
}
export function APIKeyFromJSON(json) {
    return APIKeyFromJSONTyped(json, false);
}
export function APIKeyFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'userAddress': json['user_address'] == null ? undefined : json['user_address'],
        'apiKey': json['api_key'] == null ? undefined : json['api_key'],
    };
}
export function APIKeyToJSON(json) {
    return APIKeyToJSONTyped(json, false);
}
export function APIKeyToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'user_address': value['userAddress'],
        'api_key': value['apiKey'],
    };
}
