/* tslint:disable */
/* eslint-disable */
/**
 * Crestal dashboard API - /crestal - OpenAPI 3.0
 * This is a crestal-dashboard-backend server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatRequest
 */
export interface ChatRequest {
    /**
     * Message content for the request.
     * @type {string}
     * @memberof ChatRequest
     */
    message?: string;
    /**
     * Project identifier.
     * @type {string}
     * @memberof ChatRequest
     */
    projectId: string;
    /**
     * User's blockchain address in hexadecimal format.
     * @type {string}
     * @memberof ChatRequest
     */
    userAddress: string;
}

/**
 * Check if a given object implements the ChatRequest interface.
 */
export function instanceOfChatRequest(value: object): value is ChatRequest {
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('userAddress' in value) || value['userAddress'] === undefined) return false;
    return true;
}

export function ChatRequestFromJSON(json: any): ChatRequest {
    return ChatRequestFromJSONTyped(json, false);
}

export function ChatRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'projectId': json['project_id'],
        'userAddress': json['user_address'],
    };
}

  export function ChatRequestToJSON(json: any): ChatRequest {
      return ChatRequestToJSONTyped(json, false);
  }

  export function ChatRequestToJSONTyped(value?: ChatRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'project_id': value['projectId'],
        'user_address': value['userAddress'],
    };
}

