/* tslint:disable */
/* eslint-disable */
/**
 * Crestal dashboard API - /crestal - OpenAPI 3.0
 * This is a crestal-dashboard-backend server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HistoryData } from './HistoryData';
import {
    HistoryDataFromJSON,
    HistoryDataFromJSONTyped,
    HistoryDataToJSON,
    HistoryDataToJSONTyped,
} from './HistoryData';

/**
 * 
 * @export
 * @interface DAHistoryData
 */
export interface DAHistoryData {
    /**
     * DA name ex: NearDA
     * @type {string}
     * @memberof DAHistoryData
     */
    daName?: string;
    /**
     * DA graph history data
     * @type {Array<HistoryData>}
     * @memberof DAHistoryData
     */
    historyData?: Array<HistoryData>;
}

/**
 * Check if a given object implements the DAHistoryData interface.
 */
export function instanceOfDAHistoryData(value: object): value is DAHistoryData {
    return true;
}

export function DAHistoryDataFromJSON(json: any): DAHistoryData {
    return DAHistoryDataFromJSONTyped(json, false);
}

export function DAHistoryDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): DAHistoryData {
    if (json == null) {
        return json;
    }
    return {
        
        'daName': json['da_name'] == null ? undefined : json['da_name'],
        'historyData': json['history_data'] == null ? undefined : ((json['history_data'] as Array<any>).map(HistoryDataFromJSON)),
    };
}

  export function DAHistoryDataToJSON(json: any): DAHistoryData {
      return DAHistoryDataToJSONTyped(json, false);
  }

  export function DAHistoryDataToJSONTyped(value?: DAHistoryData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'da_name': value['daName'],
        'history_data': value['historyData'] == null ? undefined : ((value['historyData'] as Array<any>).map(HistoryDataToJSON)),
    };
}

