/* tslint:disable */
/* eslint-disable */
/**
 * Crestal dashboard API - /crestal - OpenAPI 3.0
 * This is a crestal-dashboard-backend server.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DeploymentFromJSON, DeploymentToJSON, } from './Deployment';
/**
 * Check if a given object implements the Deployments interface.
 */
export function instanceOfDeployments(value) {
    return true;
}
export function DeploymentsFromJSON(json) {
    return DeploymentsFromJSONTyped(json, false);
}
export function DeploymentsFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'deployments': json['deployments'] == null ? undefined : (json['deployments'].map(DeploymentFromJSON)),
        'userAddress': json['user_address'] == null ? undefined : json['user_address'],
    };
}
export function DeploymentsToJSON(json) {
    return DeploymentsToJSONTyped(json, false);
}
export function DeploymentsToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'deployments': value['deployments'] == null ? undefined : (value['deployments'].map(DeploymentToJSON)),
        'user_address': value['userAddress'],
    };
}
