/* tslint:disable */
/* eslint-disable */
/**
 * Crestal dashboard API - /crestal - OpenAPI 3.0
 * This is a crestal-dashboard-backend server.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProposalFromJSON, ProposalToJSON, } from './Proposal';
/**
 * @export
 */
export const DeploymentStatusEnum = {
    Init: 'init',
    PickUp: 'pick_up',
    Deploying: 'deploying',
    Deployed: 'deployed',
    GeneratedProof: 'generated_proof'
};
/**
 * Check if a given object implements the Deployment interface.
 */
export function instanceOfDeployment(value) {
    if (!('userAddress' in value) || value['userAddress'] === undefined)
        return false;
    if (!('proposalId' in value) || value['proposalId'] === undefined)
        return false;
    return true;
}
export function DeploymentFromJSON(json) {
    return DeploymentFromJSONTyped(json, false);
}
export function DeploymentFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'id': json['id'] == null ? undefined : json['id'],
        'requestId': json['request_id'] == null ? undefined : json['request_id'],
        'userAddress': json['user_address'],
        'workerName': json['worker_name'] == null ? undefined : json['worker_name'],
        'workerUuid': json['worker_uuid'] == null ? undefined : json['worker_uuid'],
        'proposalHash': json['proposal_hash'] == null ? undefined : json['proposal_hash'],
        'proposalId': json['proposal_id'],
        'deploymentDetails': json['deployment_details'] == null ? undefined : json['deployment_details'],
        'proposal': json['proposal'] == null ? undefined : ProposalFromJSON(json['proposal']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}
export function DeploymentToJSON(json) {
    return DeploymentToJSONTyped(json, false);
}
export function DeploymentToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'id': value['id'],
        'request_id': value['requestId'],
        'user_address': value['userAddress'],
        'worker_name': value['workerName'],
        'worker_uuid': value['workerUuid'],
        'proposal_hash': value['proposalHash'],
        'proposal_id': value['proposalId'],
        'deployment_details': value['deploymentDetails'],
        'proposal': ProposalToJSON(value['proposal']),
        'status': value['status'],
    };
}
