/* tslint:disable */
/* eslint-disable */
/**
 * Crestal dashboard API - /crestal - OpenAPI 3.0
 * This is a crestal-dashboard-backend server.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DAHistoryDataFromJSON, DAHistoryDataToJSON, } from './DAHistoryData';
/**
 * Check if a given object implements the GraphDAInfoResponse interface.
 */
export function instanceOfGraphDAInfoResponse(value) {
    return true;
}
export function GraphDAInfoResponseFromJSON(json) {
    return GraphDAInfoResponseFromJSONTyped(json, false);
}
export function GraphDAInfoResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'data': json['data'] == null ? undefined : (json['data'].map(DAHistoryDataFromJSON)),
        'networkType': json['network_type'] == null ? undefined : json['network_type'],
    };
}
export function GraphDAInfoResponseToJSON(json) {
    return GraphDAInfoResponseToJSONTyped(json, false);
}
export function GraphDAInfoResponseToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'data': value['data'] == null ? undefined : (value['data'].map(DAHistoryDataToJSON)),
        'network_type': value['networkType'],
    };
}
