/* tslint:disable */
/* eslint-disable */
/**
 * Crestal dashboard API - /crestal - OpenAPI 3.0
 * This is a crestal-dashboard-backend server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IndexingProposal
 */
export interface IndexingProposal {
    /**
     * Rank of the indexing proposal.
     * @type {number}
     * @memberof IndexingProposal
     */
    rank?: number;
    /**
     * Fit score of the indexing proposal.
     * @type {number}
     * @memberof IndexingProposal
     */
    fit?: number;
}

/**
 * Check if a given object implements the IndexingProposal interface.
 */
export function instanceOfIndexingProposal(value: object): value is IndexingProposal {
    return true;
}

export function IndexingProposalFromJSON(json: any): IndexingProposal {
    return IndexingProposalFromJSONTyped(json, false);
}

export function IndexingProposalFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndexingProposal {
    if (json == null) {
        return json;
    }
    return {
        
        'rank': json['rank'] == null ? undefined : json['rank'],
        'fit': json['fit'] == null ? undefined : json['fit'],
    };
}

  export function IndexingProposalToJSON(json: any): IndexingProposal {
      return IndexingProposalToJSONTyped(json, false);
  }

  export function IndexingProposalToJSONTyped(value?: IndexingProposal | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rank': value['rank'],
        'fit': value['fit'],
    };
}

