/* tslint:disable */
/* eslint-disable */
/**
 * Crestal dashboard API - /crestal - OpenAPI 3.0
 * This is a crestal-dashboard-backend server.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DAInfoFromJSON, DAInfoToJSON, } from './DAInfo';
/**
 * Check if a given object implements the ListDAInfoResponse interface.
 */
export function instanceOfListDAInfoResponse(value) {
    return true;
}
export function ListDAInfoResponseFromJSON(json) {
    return ListDAInfoResponseFromJSONTyped(json, false);
}
export function ListDAInfoResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'daInfos': json['da_infos'] == null ? undefined : (json['da_infos'].map(DAInfoFromJSON)),
        'networkType': json['network_type'] == null ? undefined : json['network_type'],
    };
}
export function ListDAInfoResponseToJSON(json) {
    return ListDAInfoResponseToJSONTyped(json, false);
}
export function ListDAInfoResponseToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'da_infos': value['daInfos'] == null ? undefined : (value['daInfos'].map(DAInfoToJSON)),
        'network_type': value['networkType'],
    };
}
