/* tslint:disable */
/* eslint-disable */
/**
 * Crestal dashboard API - /crestal - OpenAPI 3.0
 * This is a crestal-dashboard-backend server.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Check if a given object implements the LoginRequest interface.
 */
export function instanceOfLoginRequest(value) {
    if (!('userAddress' in value) || value['userAddress'] === undefined)
        return false;
    if (!('signature' in value) || value['signature'] === undefined)
        return false;
    if (!('siweMsg' in value) || value['siweMsg'] === undefined)
        return false;
    return true;
}
export function LoginRequestFromJSON(json) {
    return LoginRequestFromJSONTyped(json, false);
}
export function LoginRequestFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'userAddress': json['user_address'],
        'signature': json['signature'],
        'siweMsg': json['siwe_msg'],
    };
}
export function LoginRequestToJSON(json) {
    return LoginRequestToJSONTyped(json, false);
}
export function LoginRequestToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'user_address': value['userAddress'],
        'signature': value['signature'],
        'siwe_msg': value['siweMsg'],
    };
}
