/* tslint:disable */
/* eslint-disable */
/**
 * Crestal dashboard API - /crestal - OpenAPI 3.0
 * This is a crestal-dashboard-backend server.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * @export
 */
export const MetadataMetricCategoryEnum = {
    PublicInfo: 'public_info',
    Unverified: 'unverified',
    Verified: 'verified'
};
/**
 * @export
 */
export const MetadataMetricValueTypeEnum = {
    String: 'string',
    Int: 'int',
    Float: 'float',
    Bool: 'bool'
};
/**
 * Check if a given object implements the MetadataMetric interface.
 */
export function instanceOfMetadataMetric(value) {
    return true;
}
export function MetadataMetricFromJSON(json) {
    return MetadataMetricFromJSONTyped(json, false);
}
export function MetadataMetricFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'id': json['id'] == null ? undefined : json['id'],
        'category': json['category'] == null ? undefined : json['category'],
        'showInChart': json['show_in_chart'] == null ? undefined : json['show_in_chart'],
        'orderInChart': json['order_in_chart'] == null ? undefined : json['order_in_chart'],
        'showInTable': json['show_in_table'] == null ? undefined : json['show_in_table'],
        'orderInTable': json['order_in_table'] == null ? undefined : json['order_in_table'],
        'fieldName': json['field_name'] == null ? undefined : json['field_name'],
        'displayName': json['display_name'] == null ? undefined : json['display_name'],
        'description': json['description'] == null ? undefined : json['description'],
        'unitInName': json['unit_in_name'] == null ? undefined : json['unit_in_name'],
        'unitInValue': json['unit_in_value'] == null ? undefined : json['unit_in_value'],
        'valueType': json['value_type'] == null ? undefined : json['value_type'],
        'valueFormat': json['value_format'] == null ? undefined : json['value_format'],
        'canSort': json['can_sort'] == null ? undefined : json['can_sort'],
    };
}
export function MetadataMetricToJSON(json) {
    return MetadataMetricToJSONTyped(json, false);
}
export function MetadataMetricToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'id': value['id'],
        'category': value['category'],
        'show_in_chart': value['showInChart'],
        'order_in_chart': value['orderInChart'],
        'show_in_table': value['showInTable'],
        'order_in_table': value['orderInTable'],
        'field_name': value['fieldName'],
        'display_name': value['displayName'],
        'description': value['description'],
        'unit_in_name': value['unitInName'],
        'unit_in_value': value['unitInValue'],
        'value_type': value['valueType'],
        'value_format': value['valueFormat'],
        'can_sort': value['canSort'],
    };
}
