/* tslint:disable */
/* eslint-disable */
/**
 * Crestal dashboard API - /crestal - OpenAPI 3.0
 * This is a crestal-dashboard-backend server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MetadataMetric
 */
export interface MetadataMetric {
    /**
     * Unique identifier for the metric.
     * @type {number}
     * @memberof MetadataMetric
     */
    id?: number;
    /**
     * Category of the metadata metric.
     * @type {string}
     * @memberof MetadataMetric
     */
    category?: MetadataMetricCategoryEnum;
    /**
     * Indicates if this metric should be shown in charts.
     * @type {boolean}
     * @memberof MetadataMetric
     */
    showInChart?: boolean;
    /**
     * Position in chart, where smaller values are closer to the front.
     * @type {number}
     * @memberof MetadataMetric
     */
    orderInChart?: number;
    /**
     * Indicates if this metric should be shown in tables.
     * @type {boolean}
     * @memberof MetadataMetric
     */
    showInTable?: boolean;
    /**
     * Position in table, where smaller values are closer to the front.
     * @type {number}
     * @memberof MetadataMetric
     */
    orderInTable?: number;
    /**
     * Field name in the API JSON response.
     * @type {string}
     * @memberof MetadataMetric
     */
    fieldName?: string;
    /**
     * Name displayed on the user interface.
     * @type {string}
     * @memberof MetadataMetric
     */
    displayName?: string;
    /**
     * Tooltip description displayed when the cursor hovers over the title.
     * @type {string}
     * @memberof MetadataMetric
     */
    description?: string;
    /**
     * Units displayed next to the name for better styling control.
     * @type {string}
     * @memberof MetadataMetric
     */
    unitInName?: string;
    /**
     * Units displayed directly with the value.
     * @type {string}
     * @memberof MetadataMetric
     */
    unitInValue?: string;
    /**
     * Data type of the metric value.
     * @type {string}
     * @memberof MetadataMetric
     */
    valueType?: MetadataMetricValueTypeEnum;
    /**
     * Format specification for the value.
     * @type {string}
     * @memberof MetadataMetric
     */
    valueFormat?: string;
    /**
     * Indicates if the metric can be sorted.
     * @type {boolean}
     * @memberof MetadataMetric
     */
    canSort?: boolean;
}


/**
 * @export
 */
export const MetadataMetricCategoryEnum = {
    PublicInfo: 'public_info',
    Unverified: 'unverified',
    Verified: 'verified'
} as const;
export type MetadataMetricCategoryEnum = typeof MetadataMetricCategoryEnum[keyof typeof MetadataMetricCategoryEnum];

/**
 * @export
 */
export const MetadataMetricValueTypeEnum = {
    String: 'string',
    Int: 'int',
    Float: 'float',
    Bool: 'bool'
} as const;
export type MetadataMetricValueTypeEnum = typeof MetadataMetricValueTypeEnum[keyof typeof MetadataMetricValueTypeEnum];


/**
 * Check if a given object implements the MetadataMetric interface.
 */
export function instanceOfMetadataMetric(value: object): value is MetadataMetric {
    return true;
}

export function MetadataMetricFromJSON(json: any): MetadataMetric {
    return MetadataMetricFromJSONTyped(json, false);
}

export function MetadataMetricFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetadataMetric {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'category': json['category'] == null ? undefined : json['category'],
        'showInChart': json['show_in_chart'] == null ? undefined : json['show_in_chart'],
        'orderInChart': json['order_in_chart'] == null ? undefined : json['order_in_chart'],
        'showInTable': json['show_in_table'] == null ? undefined : json['show_in_table'],
        'orderInTable': json['order_in_table'] == null ? undefined : json['order_in_table'],
        'fieldName': json['field_name'] == null ? undefined : json['field_name'],
        'displayName': json['display_name'] == null ? undefined : json['display_name'],
        'description': json['description'] == null ? undefined : json['description'],
        'unitInName': json['unit_in_name'] == null ? undefined : json['unit_in_name'],
        'unitInValue': json['unit_in_value'] == null ? undefined : json['unit_in_value'],
        'valueType': json['value_type'] == null ? undefined : json['value_type'],
        'valueFormat': json['value_format'] == null ? undefined : json['value_format'],
        'canSort': json['can_sort'] == null ? undefined : json['can_sort'],
    };
}

  export function MetadataMetricToJSON(json: any): MetadataMetric {
      return MetadataMetricToJSONTyped(json, false);
  }

  export function MetadataMetricToJSONTyped(value?: MetadataMetric | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'category': value['category'],
        'show_in_chart': value['showInChart'],
        'order_in_chart': value['orderInChart'],
        'show_in_table': value['showInTable'],
        'order_in_table': value['orderInTable'],
        'field_name': value['fieldName'],
        'display_name': value['displayName'],
        'description': value['description'],
        'unit_in_name': value['unitInName'],
        'unit_in_value': value['unitInValue'],
        'value_type': value['valueType'],
        'value_format': value['valueFormat'],
        'can_sort': value['canSort'],
    };
}

