/* tslint:disable */
/* eslint-disable */
/**
 * Crestal dashboard API - /crestal - OpenAPI 3.0
 * This is a crestal-dashboard-backend server.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectResourceFromJSON, ProjectResourceToJSON, } from './ProjectResource';
/**
 * Check if a given object implements the Projects interface.
 */
export function instanceOfProjects(value) {
    return true;
}
export function ProjectsFromJSON(json) {
    return ProjectsFromJSONTyped(json, false);
}
export function ProjectsFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'projects': json['projects'] == null ? undefined : (json['projects'].map(ProjectResourceFromJSON)),
        'userAddress': json['user_address'] == null ? undefined : json['user_address'],
    };
}
export function ProjectsToJSON(json) {
    return ProjectsToJSONTyped(json, false);
}
export function ProjectsToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'projects': value['projects'] == null ? undefined : (value['projects'].map(ProjectResourceToJSON)),
        'user_address': value['userAddress'],
    };
}
