/* tslint:disable */
/* eslint-disable */
/**
 * Crestal dashboard API - /crestal - OpenAPI 3.0
 * This is a crestal-dashboard-backend server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectResource } from './ProjectResource';
import {
    ProjectResourceFromJSON,
    ProjectResourceFromJSONTyped,
    ProjectResourceToJSON,
    ProjectResourceToJSONTyped,
} from './ProjectResource';

/**
 * 
 * @export
 * @interface Projects
 */
export interface Projects {
    /**
     * 
     * @type {Array<ProjectResource>}
     * @memberof Projects
     */
    projects?: Array<ProjectResource>;
    /**
     * User's blockchain address in hexadecimal format.
     * @type {string}
     * @memberof Projects
     */
    userAddress?: string;
}

/**
 * Check if a given object implements the Projects interface.
 */
export function instanceOfProjects(value: object): value is Projects {
    return true;
}

export function ProjectsFromJSON(json: any): Projects {
    return ProjectsFromJSONTyped(json, false);
}

export function ProjectsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Projects {
    if (json == null) {
        return json;
    }
    return {
        
        'projects': json['projects'] == null ? undefined : ((json['projects'] as Array<any>).map(ProjectResourceFromJSON)),
        'userAddress': json['user_address'] == null ? undefined : json['user_address'],
    };
}

  export function ProjectsToJSON(json: any): Projects {
      return ProjectsToJSONTyped(json, false);
  }

  export function ProjectsToJSONTyped(value?: Projects | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'projects': value['projects'] == null ? undefined : ((value['projects'] as Array<any>).map(ProjectResourceToJSON)),
        'user_address': value['userAddress'],
    };
}

