/* tslint:disable */
/* eslint-disable */
/**
 * Crestal dashboard API - /crestal - OpenAPI 3.0
 * This is a crestal-dashboard-backend server.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SolverFromJSON, SolverToJSON, } from './Solver';
import { WorkerFromJSON, WorkerToJSON, } from './Worker';
/**
 * Check if a given object implements the ProjectGetResponse interface.
 */
export function instanceOfProjectGetResponse(value) {
    return true;
}
export function ProjectGetResponseFromJSON(json) {
    return ProjectGetResponseFromJSONTyped(json, false);
}
export function ProjectGetResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'proposedSolver': json['proposed_solver'] == null ? undefined : SolverFromJSON(json['proposed_solver']),
        'deployedWorkers': json['deployed_workers'] == null ? undefined : (json['deployed_workers'].map(WorkerFromJSON)),
    };
}
export function ProjectGetResponseToJSON(json) {
    return ProjectGetResponseToJSONTyped(json, false);
}
export function ProjectGetResponseToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'proposed_solver': SolverToJSON(value['proposedSolver']),
        'deployed_workers': value['deployedWorkers'] == null ? undefined : (value['deployedWorkers'].map(WorkerToJSON)),
    };
}
