/* tslint:disable */
/* eslint-disable */
/**
 * Crestal dashboard API - /crestal - OpenAPI 3.0
 * This is a crestal-dashboard-backend server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Proposal
 */
export interface Proposal {
    /**
     * Initial cost to deploy this proposal.
     * @type {number}
     * @memberof Proposal
     */
    initCost?: number;
    /**
     * Maintenance cost for this proposal.
     * @type {number}
     * @memberof Proposal
     */
    maintenanceCost?: number;
    /**
     * Payment period for the proposal.
     * @type {number}
     * @memberof Proposal
     */
    payPeriod?: number;
    /**
     * Currency accepted for payment.
     * @type {string}
     * @memberof Proposal
     */
    acceptCurrency?: string;
    /**
     * Cost in USD.
     * @type {number}
     * @memberof Proposal
     */
    cost?: number;
    /**
     * Fit score of the proposal.
     * @type {number}
     * @memberof Proposal
     */
    fit?: number;
    /**
     * Throughput in megabytes per second.
     * @type {number}
     * @memberof Proposal
     */
    throughput?: number;
    /**
     * Uptime in seconds.
     * @type {number}
     * @memberof Proposal
     */
    sla?: number;
    /**
     * Proposal error rate.
     * @type {number}
     * @memberof Proposal
     */
    errorRate?: number;
    /**
     * Rank of the proposal.
     * @type {number}
     * @memberof Proposal
     */
    rank?: number;
    /**
     * Additional attributes of the proposal, including setup details.
     * @type {object}
     * @memberof Proposal
     */
    extraAttribute?: object;
}

/**
 * Check if a given object implements the Proposal interface.
 */
export function instanceOfProposal(value: object): value is Proposal {
    return true;
}

export function ProposalFromJSON(json: any): Proposal {
    return ProposalFromJSONTyped(json, false);
}

export function ProposalFromJSONTyped(json: any, ignoreDiscriminator: boolean): Proposal {
    if (json == null) {
        return json;
    }
    return {
        
        'initCost': json['init_cost'] == null ? undefined : json['init_cost'],
        'maintenanceCost': json['maintenance_cost'] == null ? undefined : json['maintenance_cost'],
        'payPeriod': json['pay_period'] == null ? undefined : json['pay_period'],
        'acceptCurrency': json['accept_currency'] == null ? undefined : json['accept_currency'],
        'cost': json['cost'] == null ? undefined : json['cost'],
        'fit': json['fit'] == null ? undefined : json['fit'],
        'throughput': json['throughput'] == null ? undefined : json['throughput'],
        'sla': json['sla'] == null ? undefined : json['sla'],
        'errorRate': json['error_rate'] == null ? undefined : json['error_rate'],
        'rank': json['rank'] == null ? undefined : json['rank'],
        'extraAttribute': json['extra_attribute'] == null ? undefined : json['extra_attribute'],
    };
}

  export function ProposalToJSON(json: any): Proposal {
      return ProposalToJSONTyped(json, false);
  }

  export function ProposalToJSONTyped(value?: Proposal | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'init_cost': value['initCost'],
        'maintenance_cost': value['maintenanceCost'],
        'pay_period': value['payPeriod'],
        'accept_currency': value['acceptCurrency'],
        'cost': value['cost'],
        'fit': value['fit'],
        'throughput': value['throughput'],
        'sla': value['sla'],
        'error_rate': value['errorRate'],
        'rank': value['rank'],
        'extra_attribute': value['extraAttribute'],
    };
}

