/* tslint:disable */
/* eslint-disable */
/**
 * Crestal dashboard API - /crestal - OpenAPI 3.0
 * This is a crestal-dashboard-backend server.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * @export
 */
export const QuestsActivityActionEnum = {
    Login: 'login',
    Interact: 'interact',
    ChatComplete: 'chat.complete',
    ChatHalf: 'chat.half',
    RequestProposal: 'request.proposal',
    DeployProposal: 'deploy.proposal',
    DeploymentUse: 'deployment.use',
    Feedback: 'feedback'
};
/**
 * Check if a given object implements the Quests interface.
 */
export function instanceOfQuests(value) {
    return true;
}
export function QuestsFromJSON(json) {
    return QuestsFromJSONTyped(json, false);
}
export function QuestsFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'id': json['id'] == null ? undefined : json['id'],
        'category': json['category'] == null ? undefined : json['category'],
        'level': json['level'] == null ? undefined : json['level'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'rocks': json['rocks'] == null ? undefined : json['rocks'],
        'activityAction': json['activity_action'] == null ? undefined : json['activity_action'],
    };
}
export function QuestsToJSON(json) {
    return QuestsToJSONTyped(json, false);
}
export function QuestsToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'id': value['id'],
        'category': value['category'],
        'level': value['level'],
        'title': value['title'],
        'description': value['description'],
        'rocks': value['rocks'],
        'activity_action': value['activityAction'],
    };
}
