/* tslint:disable */
/* eslint-disable */
/**
 * Crestal dashboard API - /crestal - OpenAPI 3.0
 * This is a crestal-dashboard-backend server.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Check if a given object implements the Score interface.
 */
export function instanceOfScore(value) {
    return true;
}
export function ScoreFromJSON(json) {
    return ScoreFromJSONTyped(json, false);
}
export function ScoreFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'userAddress': json['user_address'] == null ? undefined : json['user_address'],
        'totalPoint': json['total_point'] == null ? undefined : json['total_point'],
        'rank': json['rank'] == null ? undefined : json['rank'],
    };
}
export function ScoreToJSON(json) {
    return ScoreToJSONTyped(json, false);
}
export function ScoreToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'user_address': value['userAddress'],
        'total_point': value['totalPoint'],
        'rank': value['rank'],
    };
}
