/* tslint:disable */
/* eslint-disable */
/**
 * Crestal dashboard API - /crestal - OpenAPI 3.0
 * This is a crestal-dashboard-backend server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Score
 */
export interface Score {
    /**
     * User's blockchain address in hexadecimal format.
     * @type {string}
     * @memberof Score
     */
    userAddress?: string;
    /**
     * Total award points received.
     * @type {number}
     * @memberof Score
     */
    totalPoint?: number;
    /**
     * User's rank based on points.
     * @type {number}
     * @memberof Score
     */
    rank?: number;
}

/**
 * Check if a given object implements the Score interface.
 */
export function instanceOfScore(value: object): value is Score {
    return true;
}

export function ScoreFromJSON(json: any): Score {
    return ScoreFromJSONTyped(json, false);
}

export function ScoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): Score {
    if (json == null) {
        return json;
    }
    return {
        
        'userAddress': json['user_address'] == null ? undefined : json['user_address'],
        'totalPoint': json['total_point'] == null ? undefined : json['total_point'],
        'rank': json['rank'] == null ? undefined : json['rank'],
    };
}

  export function ScoreToJSON(json: any): Score {
      return ScoreToJSONTyped(json, false);
  }

  export function ScoreToJSONTyped(value?: Score | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_address': value['userAddress'],
        'total_point': value['totalPoint'],
        'rank': value['rank'],
    };
}

