/* tslint:disable */
/* eslint-disable */
/**
 * Crestal dashboard API - /crestal - OpenAPI 3.0
 * This is a crestal-dashboard-backend server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Solver
 */
export interface Solver {
    /**
     * Solver's blockchain address in hexadecimal format.
     * @type {string}
     * @memberof Solver
     */
    address?: string;
    /**
     * Unique identifier (UUID) of the solver.
     * @type {string}
     * @memberof Solver
     */
    uuid?: string;
    /**
     * Name of the solver.
     * @type {string}
     * @memberof Solver
     */
    name?: string;
    /**
     * Reputation score of the solver.
     * @type {number}
     * @memberof Solver
     */
    reputation?: number;
    /**
     * URL of the solver's logo.
     * @type {string}
     * @memberof Solver
     */
    logoUrl?: string;
    /**
     * Total amount staked by the solver.
     * @type {number}
     * @memberof Solver
     */
    totalStaked?: number;
}

/**
 * Check if a given object implements the Solver interface.
 */
export function instanceOfSolver(value: object): value is Solver {
    return true;
}

export function SolverFromJSON(json: any): Solver {
    return SolverFromJSONTyped(json, false);
}

export function SolverFromJSONTyped(json: any, ignoreDiscriminator: boolean): Solver {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'] == null ? undefined : json['address'],
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
        'name': json['name'] == null ? undefined : json['name'],
        'reputation': json['reputation'] == null ? undefined : json['reputation'],
        'logoUrl': json['logo_url'] == null ? undefined : json['logo_url'],
        'totalStaked': json['total_staked'] == null ? undefined : json['total_staked'],
    };
}

  export function SolverToJSON(json: any): Solver {
      return SolverToJSONTyped(json, false);
  }

  export function SolverToJSONTyped(value?: Solver | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'uuid': value['uuid'],
        'name': value['name'],
        'reputation': value['reputation'],
        'logo_url': value['logoUrl'],
        'total_staked': value['totalStaked'],
    };
}

