/* tslint:disable */
/* eslint-disable */
/**
 * Crestal dashboard API - /crestal - OpenAPI 3.0
 * This is a crestal-dashboard-backend server.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SolversProposalFromJSON, SolversProposalToJSON, } from './SolversProposal';
/**
 * Check if a given object implements the SolversProposalsResponse interface.
 */
export function instanceOfSolversProposalsResponse(value) {
    return true;
}
export function SolversProposalsResponseFromJSON(json) {
    return SolversProposalsResponseFromJSONTyped(json, false);
}
export function SolversProposalsResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'proposals': json['proposals'] == null ? undefined : (json['proposals'].map(SolversProposalFromJSON)),
        'requestId': json['request_id'] == null ? undefined : json['request_id'],
    };
}
export function SolversProposalsResponseToJSON(json) {
    return SolversProposalsResponseToJSONTyped(json, false);
}
export function SolversProposalsResponseToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'proposals': value['proposals'] == null ? undefined : (value['proposals'].map(SolversProposalToJSON)),
        'request_id': value['requestId'],
    };
}
