/* tslint:disable */
/* eslint-disable */
/**
 * Crestal dashboard API - /crestal - OpenAPI 3.0
 * This is a crestal-dashboard-backend server.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProposalFromJSON, ProposalToJSON, } from './Proposal';
/**
 * Check if a given object implements the SolverProposal interface.
 */
export function instanceOfSolverProposal(value) {
    return true;
}
export function SolverProposalFromJSON(json) {
    return SolverProposalFromJSONTyped(json, false);
}
export function SolverProposalFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'proposals': json['proposals'] == null ? undefined : (json['proposals'].map(ProposalFromJSON)),
        'solverUuid': json['solver_uuid'] == null ? undefined : json['solver_uuid'],
        'solverReputation': json['solver_reputation'] == null ? undefined : json['solver_reputation'],
    };
}
export function SolverProposalToJSON(json) {
    return SolverProposalToJSONTyped(json, false);
}
export function SolverProposalToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'proposals': value['proposals'] == null ? undefined : (value['proposals'].map(ProposalToJSON)),
        'solver_uuid': value['solverUuid'],
        'solver_reputation': value['solverReputation'],
    };
}
