/* tslint:disable */
/* eslint-disable */
/**
 * Crestal dashboard API - /crestal - OpenAPI 3.0
 * This is a crestal-dashboard-backend server.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SolverProposalFromJSON, SolverProposalToJSON, } from './SolverProposal';
/**
 * Check if a given object implements the SolverProposals interface.
 */
export function instanceOfSolverProposals(value) {
    return true;
}
export function SolverProposalsFromJSON(json) {
    return SolverProposalsFromJSONTyped(json, false);
}
export function SolverProposalsFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'solverProposals': json['solver_proposals'] == null ? undefined : (json['solver_proposals'].map(SolverProposalFromJSON)),
    };
}
export function SolverProposalsToJSON(json) {
    return SolverProposalsToJSONTyped(json, false);
}
export function SolverProposalsToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'solver_proposals': value['solverProposals'] == null ? undefined : (value['solverProposals'].map(SolverProposalToJSON)),
    };
}
