/* tslint:disable */
/* eslint-disable */
/**
 * Crestal dashboard API - /crestal - OpenAPI 3.0
 * This is a crestal-dashboard-backend server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SolverProposal } from './SolverProposal';
import {
    SolverProposalFromJSON,
    SolverProposalFromJSONTyped,
    SolverProposalToJSON,
    SolverProposalToJSONTyped,
} from './SolverProposal';

/**
 * Will be deprecated in the future once solver development is complete.
 * @export
 * @interface SolverProposals
 */
export interface SolverProposals {
    /**
     * 
     * @type {Array<SolverProposal>}
     * @memberof SolverProposals
     */
    solverProposals?: Array<SolverProposal>;
}

/**
 * Check if a given object implements the SolverProposals interface.
 */
export function instanceOfSolverProposals(value: object): value is SolverProposals {
    return true;
}

export function SolverProposalsFromJSON(json: any): SolverProposals {
    return SolverProposalsFromJSONTyped(json, false);
}

export function SolverProposalsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SolverProposals {
    if (json == null) {
        return json;
    }
    return {
        
        'solverProposals': json['solver_proposals'] == null ? undefined : ((json['solver_proposals'] as Array<any>).map(SolverProposalFromJSON)),
    };
}

  export function SolverProposalsToJSON(json: any): SolverProposals {
      return SolverProposalsToJSONTyped(json, false);
  }

  export function SolverProposalsToJSONTyped(value?: SolverProposals | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'solver_proposals': value['solverProposals'] == null ? undefined : ((value['solverProposals'] as Array<any>).map(SolverProposalToJSON)),
    };
}

