/* tslint:disable */
/* eslint-disable */
/**
 * Crestal dashboard API - /crestal - OpenAPI 3.0
 * This is a crestal-dashboard-backend server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SolversProposal } from './SolversProposal';
import {
    SolversProposalFromJSON,
    SolversProposalFromJSONTyped,
    SolversProposalToJSON,
    SolversProposalToJSONTyped,
} from './SolversProposal';

/**
 * 
 * @export
 * @interface SolversProposalsResponse
 */
export interface SolversProposalsResponse {
    /**
     * 
     * @type {Array<SolversProposal>}
     * @memberof SolversProposalsResponse
     */
    proposals?: Array<SolversProposal>;
    /**
     * Unique request ID.
     * @type {string}
     * @memberof SolversProposalsResponse
     */
    requestId?: string;
}

/**
 * Check if a given object implements the SolversProposalsResponse interface.
 */
export function instanceOfSolversProposalsResponse(value: object): value is SolversProposalsResponse {
    return true;
}

export function SolversProposalsResponseFromJSON(json: any): SolversProposalsResponse {
    return SolversProposalsResponseFromJSONTyped(json, false);
}

export function SolversProposalsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SolversProposalsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'proposals': json['proposals'] == null ? undefined : ((json['proposals'] as Array<any>).map(SolversProposalFromJSON)),
        'requestId': json['request_id'] == null ? undefined : json['request_id'],
    };
}

  export function SolversProposalsResponseToJSON(json: any): SolversProposalsResponse {
      return SolversProposalsResponseToJSONTyped(json, false);
  }

  export function SolversProposalsResponseToJSONTyped(value?: SolversProposalsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'proposals': value['proposals'] == null ? undefined : ((value['proposals'] as Array<any>).map(SolversProposalToJSON)),
        'request_id': value['requestId'],
    };
}

