/* tslint:disable */
/* eslint-disable */
/**
 * Crestal dashboard API - /crestal - OpenAPI 3.0
 * This is a crestal-dashboard-backend server.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Check if a given object implements the Token interface.
 */
export function instanceOfToken(value) {
    return true;
}
export function TokenFromJSON(json) {
    return TokenFromJSONTyped(json, false);
}
export function TokenFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'refreshToken': json['refresh_token'] == null ? undefined : json['refresh_token'],
        'accessToken': json['access_token'] == null ? undefined : json['access_token'],
    };
}
export function TokenToJSON(json) {
    return TokenToJSONTyped(json, false);
}
export function TokenToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'refresh_token': value['refreshToken'],
        'access_token': value['accessToken'],
    };
}
