/* tslint:disable */
/* eslint-disable */
/**
 * Crestal dashboard API - /crestal - OpenAPI 3.0
 * This is a crestal-dashboard-backend server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserPostQuest } from './UserPostQuest';
import {
    UserPostQuestFromJSON,
    UserPostQuestFromJSONTyped,
    UserPostQuestToJSON,
    UserPostQuestToJSONTyped,
} from './UserPostQuest';

/**
 * 
 * @export
 * @interface UserPostQuests
 */
export interface UserPostQuests {
    /**
     * 
     * @type {Array<UserPostQuest>}
     * @memberof UserPostQuests
     */
    userQuests?: Array<UserPostQuest>;
}

/**
 * Check if a given object implements the UserPostQuests interface.
 */
export function instanceOfUserPostQuests(value: object): value is UserPostQuests {
    return true;
}

export function UserPostQuestsFromJSON(json: any): UserPostQuests {
    return UserPostQuestsFromJSONTyped(json, false);
}

export function UserPostQuestsFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserPostQuests {
    if (json == null) {
        return json;
    }
    return {
        
        'userQuests': json['user_quests'] == null ? undefined : ((json['user_quests'] as Array<any>).map(UserPostQuestFromJSON)),
    };
}

  export function UserPostQuestsToJSON(json: any): UserPostQuests {
      return UserPostQuestsToJSONTyped(json, false);
  }

  export function UserPostQuestsToJSONTyped(value?: UserPostQuests | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_quests': value['userQuests'] == null ? undefined : ((value['userQuests'] as Array<any>).map(UserPostQuestToJSON)),
    };
}

