/* tslint:disable */
/* eslint-disable */
/**
 * Crestal dashboard API - /crestal - OpenAPI 3.0
 * This is a crestal-dashboard-backend server.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Check if a given object implements the User interface.
 */
export function instanceOfUser(value) {
    return true;
}
export function UserFromJSON(json) {
    return UserFromJSONTyped(json, false);
}
export function UserFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'userAddress': json['user_address'] == null ? undefined : json['user_address'],
        'totalPoint': json['total_point'] == null ? undefined : json['total_point'],
        'quests': json['quests'] == null ? undefined : json['quests'],
        'rank': json['rank'] == null ? undefined : json['rank'],
        'github': json['github'] == null ? undefined : json['github'],
        'totalInvited': json['total_invited'] == null ? undefined : json['total_invited'],
        'subscribe': json['subscribe'] == null ? undefined : json['subscribe'],
    };
}
export function UserToJSON(json) {
    return UserToJSONTyped(json, false);
}
export function UserToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'user_address': value['userAddress'],
        'total_point': value['totalPoint'],
        'quests': value['quests'],
        'rank': value['rank'],
        'github': value['github'],
        'total_invited': value['totalInvited'],
        'subscribe': value['subscribe'],
    };
}
