/* tslint:disable */
/* eslint-disable */
/**
 * Crestal dashboard API - /crestal - OpenAPI 3.0
 * This is a crestal-dashboard-backend server.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserPostQuestFromJSON, UserPostQuestToJSON, } from './UserPostQuest';
/**
 * Check if a given object implements the UserPostQuests interface.
 */
export function instanceOfUserPostQuests(value) {
    return true;
}
export function UserPostQuestsFromJSON(json) {
    return UserPostQuestsFromJSONTyped(json, false);
}
export function UserPostQuestsFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'userQuests': json['user_quests'] == null ? undefined : (json['user_quests'].map(UserPostQuestFromJSON)),
    };
}
export function UserPostQuestsToJSON(json) {
    return UserPostQuestsToJSONTyped(json, false);
}
export function UserPostQuestsToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'user_quests': value['userQuests'] == null ? undefined : (value['userQuests'].map(UserPostQuestToJSON)),
    };
}
