/* tslint:disable */
/* eslint-disable */
/**
 * Crestal dashboard API - /crestal - OpenAPI 3.0
 * This is a crestal-dashboard-backend server.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Check if a given object implements the UserQuest interface.
 */
export function instanceOfUserQuest(value) {
    return true;
}
export function UserQuestFromJSON(json) {
    return UserQuestFromJSONTyped(json, false);
}
export function UserQuestFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'startTime': json['start_time'] == null ? undefined : json['start_time'],
        'endTime': json['end_time'] == null ? undefined : json['end_time'],
        'baseRocks': json['base_rocks'] == null ? undefined : json['base_rocks'],
        'referRocks': json['refer_rocks'] == null ? undefined : json['refer_rocks'],
    };
}
export function UserQuestToJSON(json) {
    return UserQuestToJSONTyped(json, false);
}
export function UserQuestToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'start_time': value['startTime'],
        'end_time': value['endTime'],
        'base_rocks': value['baseRocks'],
        'refer_rocks': value['referRocks'],
    };
}
