/* tslint:disable */
/* eslint-disable */
/**
 * Crestal dashboard API - /crestal - OpenAPI 3.0
 * This is a crestal-dashboard-backend server.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QuestsFromJSON, QuestsToJSON, } from './Quests';
/**
 * Check if a given object implements the WeeklyQuests interface.
 */
export function instanceOfWeeklyQuests(value) {
    return true;
}
export function WeeklyQuestsFromJSON(json) {
    return WeeklyQuestsFromJSONTyped(json, false);
}
export function WeeklyQuestsFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'startTime': json['start_time'] == null ? undefined : json['start_time'],
        'endTime': json['end_time'] == null ? undefined : json['end_time'],
        'quests': json['quests'] == null ? undefined : (json['quests'].map(QuestsFromJSON)),
    };
}
export function WeeklyQuestsToJSON(json) {
    return WeeklyQuestsToJSONTyped(json, false);
}
export function WeeklyQuestsToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'start_time': value['startTime'],
        'end_time': value['endTime'],
        'quests': value['quests'] == null ? undefined : (value['quests'].map(QuestsToJSON)),
    };
}
