/* tslint:disable */
/* eslint-disable */
/**
 * Crestal dashboard API - /crestal - OpenAPI 3.0
 * This is a crestal-dashboard-backend server.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * @export
 */
export const WhiteListNetworkTypeEnum = {
    Mainnet: 'Mainnet',
    Testnet: 'Testnet'
};
/**
 * Check if a given object implements the WhiteList interface.
 */
export function instanceOfWhiteList(value) {
    return true;
}
export function WhiteListFromJSON(json) {
    return WhiteListFromJSONTyped(json, false);
}
export function WhiteListFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'address': json['address'] == null ? undefined : json['address'],
        'name': json['name'] == null ? undefined : json['name'],
        'networkType': json['network_type'] == null ? undefined : json['network_type'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
    };
}
export function WhiteListToJSON(json) {
    return WhiteListToJSONTyped(json, false);
}
export function WhiteListToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'address': value['address'],
        'name': value['name'],
        'network_type': value['networkType'],
        'created_at': value['createdAt'],
    };
}
