name: Update SDK

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Check for updates daily at midnight UTC
  repository_dispatch:
    types: [update-api-file]

jobs:
  update_sdk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout auth-sdk repository
        uses: actions/checkout@v2

      - name: Fetch the current `api.yaml` from the docs repo
        run: |
          curl -H "Authorization: token ${{ secrets.AUTOGEN_GITHUB_TOKEN }}" -L \
            https://raw.githubusercontent.com/crestalnetwork/docs/main/mintlify-docs/api-reference/api.yaml \
            -o new_api.yaml

      - name: Check for API changes
        id: check_changes
        run: |
          if [ -f "typescript-sdk/api.yaml" ]; then
            if diff typescript-sdk/api.yaml new_api.yaml > /dev/null; then
              echo "api_changed=false" >> $GITHUB_ENV
            else
              echo "api_changed=true" >> $GITHUB_ENV
            fi
          else
            echo "api_changed=true" >> $GITHUB_ENV
        continue-on-error: true

      - name: Display API Change Status
        run: echo "API Changed: ${{ env.api_changed }}"

      - name: Generate SDK only if API changed
        if: env.api_changed == 'true'
        run: |
          echo "API has changed. Generating new SDK..."
          mv new_api.yaml api.yaml
          yarn global add @openapitools/openapi-generator-cli
          yarn openapi-generator-cli generate -i api.yaml -g typescript-fetch -o ./typescript-sdk

      - name: Commit and push changes
        if: env.api_changed == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ./typescript-sdk api.yaml
          git commit -m "Auto-update SDK based on new API file"
          git push
