/* tslint:disable */
/* eslint-disable */
/**
 * Crestal dashboard API - /crestal - OpenAPI 3.0
 * This is a crestal-dashboard-backend server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommonResponse
 */
export interface CommonResponse {
    /**
     * Descriptive message providing details about the response.
     * @type {string}
     * @memberof CommonResponse
     */
    message?: string;
    /**
     * Status of the response, indicating success or error.
     * @type {string}
     * @memberof CommonResponse
     */
    status?: string;
}

/**
 * Check if a given object implements the CommonResponse interface.
 */
export function instanceOfCommonResponse(value: object): value is CommonResponse {
    return true;
}

export function CommonResponseFromJSON(json: any): CommonResponse {
    return CommonResponseFromJSONTyped(json, false);
}

export function CommonResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

  export function CommonResponseToJSON(json: any): CommonResponse {
      return CommonResponseToJSONTyped(json, false);
  }

  export function CommonResponseToJSONTyped(value?: CommonResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'status': value['status'],
    };
}

