/* tslint:disable */
/* eslint-disable */
/**
 * Crestal dashboard API - /crestal - OpenAPI 3.0
 * This is a crestal-dashboard-backend server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginRequest
 */
export interface LoginRequest {
    /**
     * User's blockchain address in hexadecimal format.
     * @type {string}
     * @memberof LoginRequest
     */
    userAddress: string;
    /**
     * User's signature in hexadecimal format.
     * @type {string}
     * @memberof LoginRequest
     */
    signature: string;
    /**
     * SIWE message in string format.
     * @type {string}
     * @memberof LoginRequest
     */
    siweMsg: string;
}

/**
 * Check if a given object implements the LoginRequest interface.
 */
export function instanceOfLoginRequest(value: object): value is LoginRequest {
    if (!('userAddress' in value) || value['userAddress'] === undefined) return false;
    if (!('signature' in value) || value['signature'] === undefined) return false;
    if (!('siweMsg' in value) || value['siweMsg'] === undefined) return false;
    return true;
}

export function LoginRequestFromJSON(json: any): LoginRequest {
    return LoginRequestFromJSONTyped(json, false);
}

export function LoginRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userAddress': json['user_address'],
        'signature': json['signature'],
        'siweMsg': json['siwe_msg'],
    };
}

  export function LoginRequestToJSON(json: any): LoginRequest {
      return LoginRequestToJSONTyped(json, false);
  }

  export function LoginRequestToJSONTyped(value?: LoginRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_address': value['userAddress'],
        'signature': value['signature'],
        'siwe_msg': value['siweMsg'],
    };
}

