/* tslint:disable */
/* eslint-disable */
/**
 * Crestal dashboard API - /crestal - OpenAPI 3.0
 * This is a crestal-dashboard-backend server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StorageProposal
 */
export interface StorageProposal {
    /**
     * Rank of the storage proposal.
     * @type {number}
     * @memberof StorageProposal
     */
    rank?: number;
    /**
     * Fit score of the storage proposal.
     * @type {number}
     * @memberof StorageProposal
     */
    fit?: number;
}

/**
 * Check if a given object implements the StorageProposal interface.
 */
export function instanceOfStorageProposal(value: object): value is StorageProposal {
    return true;
}

export function StorageProposalFromJSON(json: any): StorageProposal {
    return StorageProposalFromJSONTyped(json, false);
}

export function StorageProposalFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageProposal {
    if (json == null) {
        return json;
    }
    return {
        
        'rank': json['rank'] == null ? undefined : json['rank'],
        'fit': json['fit'] == null ? undefined : json['fit'],
    };
}

  export function StorageProposalToJSON(json: any): StorageProposal {
      return StorageProposalToJSONTyped(json, false);
  }

  export function StorageProposalToJSONTyped(value?: StorageProposal | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rank': value['rank'],
        'fit': value['fit'],
    };
}

