/* tslint:disable */
/* eslint-disable */
/**
 * Crestal dashboard API - /crestal - OpenAPI 3.0
 * This is a crestal-dashboard-backend server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Token
 */
export interface Token {
    /**
     * Newly issued refresh token.
     * @type {string}
     * @memberof Token
     */
    refreshToken?: string;
    /**
     * Newly issued access token.
     * @type {string}
     * @memberof Token
     */
    accessToken?: string;
}

/**
 * Check if a given object implements the Token interface.
 */
export function instanceOfToken(value: object): value is Token {
    return true;
}

export function TokenFromJSON(json: any): Token {
    return TokenFromJSONTyped(json, false);
}

export function TokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): Token {
    if (json == null) {
        return json;
    }
    return {
        
        'refreshToken': json['refresh_token'] == null ? undefined : json['refresh_token'],
        'accessToken': json['access_token'] == null ? undefined : json['access_token'],
    };
}

  export function TokenToJSON(json: any): Token {
      return TokenToJSONTyped(json, false);
  }

  export function TokenToJSONTyped(value?: Token | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'refresh_token': value['refreshToken'],
        'access_token': value['accessToken'],
    };
}

