/* tslint:disable */
/* eslint-disable */
/**
 * Crestal dashboard API - /crestal - OpenAPI 3.0
 * This is a crestal-dashboard-backend server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserQuest
 */
export interface UserQuest {
    /**
     * Quest start time in UTC.
     * @type {string}
     * @memberof UserQuest
     */
    startTime?: string;
    /**
     * Quest end time in UTC.
     * @type {string}
     * @memberof UserQuest
     */
    endTime?: string;
    /**
     * Total "rocks" awarded from completing quests.
     * @type {number}
     * @memberof UserQuest
     */
    baseRocks?: number;
    /**
     * Total "rocks" awarded through referrals.
     * @type {number}
     * @memberof UserQuest
     */
    referRocks?: number;
}

/**
 * Check if a given object implements the UserQuest interface.
 */
export function instanceOfUserQuest(value: object): value is UserQuest {
    return true;
}

export function UserQuestFromJSON(json: any): UserQuest {
    return UserQuestFromJSONTyped(json, false);
}

export function UserQuestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserQuest {
    if (json == null) {
        return json;
    }
    return {
        
        'startTime': json['start_time'] == null ? undefined : json['start_time'],
        'endTime': json['end_time'] == null ? undefined : json['end_time'],
        'baseRocks': json['base_rocks'] == null ? undefined : json['base_rocks'],
        'referRocks': json['refer_rocks'] == null ? undefined : json['refer_rocks'],
    };
}

  export function UserQuestToJSON(json: any): UserQuest {
      return UserQuestToJSONTyped(json, false);
  }

  export function UserQuestToJSONTyped(value?: UserQuest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'start_time': value['startTime'],
        'end_time': value['endTime'],
        'base_rocks': value['baseRocks'],
        'refer_rocks': value['referRocks'],
    };
}

